### ISSUE TITLE
Binary package for release 1.0.1 not available on Jcenter

### ISSUE THREAD

**Issue by julienbanse** [vinaysshenoy/mugen#10]
Binary package is not available from JCenter for release 1.0.1:
https://jcenter.bintray.com/com/vinaysshenoy/mugen/1.0.1/

But for release 1.0.0, every package are available:
https://jcenter.bintray.com/com/vinaysshenoy/mugen/1.0.0/

**Comment by vinaysshenoy** [comment]
I use OSS Sonatype. Maybe Bintray just takes some time to update? I released them just yesterday, anyway.

They are available on maven.org.

**Comment by julienbanse** [comment]
Ok, I didn't know you made a release only yesterday.
It may take some time.

2015-07-13 10:58 GMT+02:00 Vinay S Shenoy <notifications@github.com>:

**Comment by vinaysshenoy** [comment]
Although, is there any specific reason you are looking for it on bintray? The binary packages should be available if you use it on gradle with the standard dependency url, no?

**Comment by vinaysshenoy** [comment]
Never mind, I tried it right now. Probably will take some time to be available.

**Comment by vinaysshenoy** [comment]
@julienbanse The AAR seems to available on jcenter now. Please check and close the issue if it's working for you.

**Comment by julienbanse** [comment]
That works !

**Comment by frostymarvelous** [comment]
Still doesn't work for me using jcenter. And we use jcenter because it is the default recommended.
