### ISSUE TITLE
support v4 22.2.0 has a bug of DialogFragment$DialogStyle, which make annotation process with DialogFragment compile fail, please update to 22.2.1

### ISSUE THREAD

**Issue by Piasy** [vinaysshenoy/mugen#13]
ref: [google code issue](https://code.google.com/p/android/issues/detail?id=175086)

**Comment by mipreamble** [comment]
@Piasy Thanks for reporting.

Update is ready. We will plan a release soon.
https://github.com/vinaysshenoy/mugen/pull/14

**Comment by vinaysshenoy** [comment]
#14 is merged. Will release by tonight.

**Comment by Piasy** [comment]
👍Great! Thanks.

**Comment by vinaysshenoy** [comment]
Released to maven with https://github.com/vinaysshenoy/mugen/releases/tag/v1.0.2
