### ISSUE TITLE
Can't get this to work with ExpandableHeightListView

### ISSUE THREAD

**Issue by tarhe** [vinaysshenoy/mugen#18]
I have the following on my Fragment

        listview = (ExpandableHeightListView)v.findViewById(R.id.listview);

        Bean = new ArrayList<Bean>();

        //mCollectionView can be a ListView, GridView, RecyclerView or any instance of AbsListView!
        BaseAttacher attacher = Mugen.with(listview, new MugenCallbacks() {
            @Override
            public void onLoadMore() {
                customLoadMoreDataFromApi();
            }

            @Override
            public boolean isLoading() {
                return isLoading;
            }

            @Override
            public boolean hasLoadedAllItems() {
                return false;
            }
        }).start();

        attacher.setLoadMoreOffset(4);
        attacher.setLoadMoreEnabled(true);
        attacher.start();

I pulled 10 items from database, so my list is filled but the LoadMore() is not called at all.

**Comment by vinaysshenoy** [comment]
@tarhe I am so sorry, I saw this just now!

Did you manage to fix the problem?

**Comment by tarhe** [comment]
Yes, I have. The issue was the ExpandableHeightListView and I was able to work around it. Thanks for this great lib.

**Comment by vinaysshenoy** [comment]
Cool! Glad you like it!

Considering the issue closed.
