### ISSUE TITLE
Can't get it work with RecyclerView

### ISSUE THREAD

**Issue by pavlospt** [vinaysshenoy/mugen#4]
I am trying to use it with a recyclerview but it doesnt seem to wanna work. below is my code:

mBaseAttacher = Mugen.with(mMessagesRecycler, new MugenCallbacks() {
            @Override
            public void onLoadMore() {
                Log.e(TAG, "Triggered load more");
                loadSomeMoreMessages();
            }

            @Override
            public boolean isLoading() {
                return isLoading;
            }

            @Override
            public boolean hasLoadedAllItems() {
                return hasLoadedAllItems;
            }
        });

        mBaseAttacher.setLoadMoreOffset(5);
        mBaseAttacher.setLoadMoreEnabled(true);
        mBaseAttacher.start(); ``

mBaseAttacher is a RecyclerviewAttacher

**Comment by vinaysshenoy** [comment]
Have you loaded the first set of items? The first set must be loaded manually. After the list gets enough items and becomes scrollable, then it starts working.

**Comment by pavlospt** [comment]
So i have to load items and then instantiate the attacher?

**Comment by vinaysshenoy** [comment]
You can instantiate the attacher at any time. The load more trigger is when the list starts scrolling and reaches towards the end, so unless there are enough items already in the list, the triggers will not get called.

I'll update the documentation to make it more clear.

**Comment by pavlospt** [comment]
The list has enough items to be scrollable but yet it doesn't seem to call "loadMore()"

**Comment by vinaysshenoy** [comment]
Can you check the value of isLoading? It should be `false` intially.

**Comment by pavlospt** [comment]
@vinaysshenoy I was setting hasLoadedAllItems to true without checking that the server has no more data to feed, so it wasn't triggering the "loadMore()".

**Comment by vinaysshenoy** [comment]
Oh, all right. Sounds good. Please report any issues if you come across any, and we'll fix them up asap.

Hope you like mugen. :-)

**Comment by pavlospt** [comment]
@vinaysshenoy Yes of course, thanks again for your work and your time!
