### ISSUE TITLE
in init() method of RecyclerViewAttacher, should use addOnScrollListener instead of setOnScrollListener

### ISSUE THREAD

**Issue by Piasy** [vinaysshenoy/mugen#9]
https://github.com/vinaysshenoy/mugen/blob/master/library/src/main/java/com/mugen/attachers/RecyclerViewAttacher.java#L24  
setOnScrollListener method of RecyclerView is deprecated, and will make other listeners not work.

**Comment by vinaysshenoy** [comment]
Right, I'll fix it and release a new version soon.

**Comment by vinaysshenoy** [comment]
Fixed in https://github.com/vinaysshenoy/mugen/releases/tag/v1.0.1.
